# -*- coding: utf-8 -*-
"""
Build comprehensive list of 370+ English Irregular Verbs with IPA phonetics, V1, V2, V3 and Vietnamese meanings.
"""

import json
import os

IRREGULAR_VERBS_RAW = [
    ("abide", "/əˈbaɪd/", "abode / abided", "/əˈboʊd/", "abode / abided", "/əˈboʊd/", "tuân theo, chịu đựng", "They promised to abide by the rules."),
    ("arise", "/əˈraɪz/", "arose", "/əˈroʊz/", "arisen", "/əˈrɪz.ən/", "xuất hiện, nảy sinh", "Problems arose during the meeting."),
    ("awake", "/əˈweɪk/", "awoke", "/əˈwoʊk/", "awoken", "/əˈwoʊ.kən/", "thức giấc, đánh thức", "She awoke early in the morning."),
    ("backslide", "/ˈbæk.slaɪd/", "backslid", "/ˈbæk.slɪd/", "backslidden / backslid", "/ˈbæk.slɪd.ən/", "tái phạm, thụt lùi", "He backslid into old habits."),
    ("be", "/biː/", "was / were", "/wɒz/ / /wɜːr/", "been", "/biːn/", "thì, là, ở", "I have been here before."),
    ("bear", "/beər/", "bore", "/bɔːr/", "borne / born", "/bɔːrn/", "chịu đựng, sinh đẻ", "She bore all the difficulties."),
    ("beat", "/biːt/", "beat", "/biːt/", "beaten", "/ˈbiː.tən/", "đánh bại, đập", "Our team beat their rivals."),
    ("become", "/bɪˈkʌm/", "became", "/bɪˈkeɪm/", "become", "/bɪˈkʌm/", "trở thành, trở nên", "She became a doctor."),
    ("befall", "/bɪˈfɔːl/", "befell", "/bɪˈfel/", "befallen", "/bɪˈfɔː.lən/", "xảy đến, giáng xuống", "A tragedy befell the town."),
    ("beget", "/bɪˈɡet/", "begot / begat", "/bɪˈɡɒt/", "begotten", "/bɪˈɡɒt.ən/", "sinh ra, gây ra", "Violence begets violence."),
    ("begin", "/bɪˈɡɪn/", "began", "/bɪˈɡæn/", "begun", "/bɪˈɡʌn/", "bắt đầu", "The lesson began at 8 AM."),
    ("behold", "/bɪˈhoʊld/", "beheld", "/bɪˈheld/", "beheld", "/bɪˈheld/", "ngắm nhìn, chiêm ngưỡng", "They beheld a wonderful sunrise."),
    ("bend", "/bend/", "bent", "/bent/", "bent", "/bent/", "bẻ cong, uốn cong", "He bent the wire into a circle."),
    ("bereave", "/bɪˈriːv/", "bereft / bereaved", "/bɪˈreft/", "bereft / bereaved", "/bɪˈreft/", "cướp đi, tước đoạt", "The accident bereaved him of his family."),
    ("beseech", "/bɪˈsiːtʃ/", "besought / beseeched", "/bɪˈsɔːt/", "besought / beseeched", "/bɪˈsɔːt/", "van xin, khẩn cầu", "They besought the king for mercy."),
    ("beset", "/bɪˈset/", "beset", "/bɪˈset/", "beset", "/bɪˈset/", "bủa vây, đeo bám", "The project was beset with difficulties."),
    ("bespeak", "/bɪˈspiːk/", "bespoke", "/bɪˈspoʊk/", "bespoken", "/bɪˈspoʊ.kən/", "chứng tỏ, đặt trước", "His calm voice bespoke confidence."),
    ("bestride", "/bɪˈstraɪd/", "bestrode", "/bɪˈstroʊd/", "bestridden", "/bɪˈstrɪd.ən/", "ngồi dạng chân, cưỡi", "He bestrode his motorbike."),
    ("bet", "/bet/", "bet / betted", "/bet/", "bet / betted", "/bet/", "đánh cược, cá cược", "I bet you ten dollars."),
    ("bid", "/bɪd/", "bid / bade", "/bɪd/ / /beɪd/", "bid / bidden", "/bɪd/ / /ˈbɪd.ən/", "trả giá, ra lệnh", "She bid $500 for the painting."),
    ("bind", "/baɪnd/", "bound", "/baʊnd/", "bound", "/baʊnd/", "buộc, trói buộc", "The contract binds both parties."),
    ("bite", "/baɪt/", "bit", "/bɪt/", "bitten", "/ˈbɪt.ən/", "cắn, ngoạm", "The dog bit his leg."),
    ("bleed", "/bliːd/", "bled", "/bled/", "bled", "/bled/", "chảy máu", "His finger bled after the cut."),
    ("blow", "/bloʊ/", "blew", "/bluː/", "blown", "/bloʊn/", "thổi", "A cold wind blew softly."),
    ("break", "/breɪk/", "broke", "/broʊk/", "broken", "/ˈbroʊ.kən/", "làm vỡ, bẻ gãy", "He broke the vase by accident."),
    ("breed", "/briːd/", "bred", "/bred/", "bred", "/bred/", "nuôi dưỡng, sinh sản", "Rabbits breed very quickly."),
    ("bring", "/brɪŋ/", "brought", "/brɔːt/", "brought", "/brɔːt/", "mang lại, đem đến", "She brought some flowers."),
    ("broadcast", "/ˈbrɔːd.kæst/", "broadcast", "/ˈbrɔːd.kæst/", "broadcast", "/ˈbrɔːd.kæst/", "phát sóng, truyền hình", "The event was broadcast live."),
    ("browbeat", "/ˈbraʊ.biːt/", "browbeat", "/ˈbraʊ.biːt/", "browbeaten", "/ˈbraʊˌbiː.tən/", "đe dọa, nạt nộ", "Do not let them browbeat you."),
    ("build", "/bɪld/", "built", "/bɪlt/", "built", "/bɪlt/", "xây dựng", "They built a new house."),
    ("burn", "/bɜːrn/", "burnt / burned", "/bɜːrnt/", "burnt / burned", "/bɜːrnt/", "đốt cháy, cháy", "The fire burnt all night."),
    ("burst", "/bɜːrst/", "burst", "/bɜːrst/", "burst", "/bɜːrst/", "nổ tung, vỡ òa", "The balloon burst with a bang."),
    ("bust", "/bʌst/", "bust / busted", "/bʌst/", "bust / busted", "/bʌst/", "làm hỏng, phá sản", "The watch is bust."),
    ("buy", "/baɪ/", "bought", "/bɔːt/", "bought", "/bɔːt/", "mua", "He bought a new laptop yesterday."),
    ("cast", "/kæst/", "cast", "/kæst/", "cast", "/kæst/", "quăng, ném, đúc", "The fisherman cast his net."),
    ("catch", "/kætʃ/", "caught", "/kɔːt/", "caught", "/kɔːt/", "bắt kịp, tóm lấy", "She caught the early bus."),
    ("chide", "/tʃaɪd/", "chid / chided", "/tʃɪd/", "chidden / chided", "/ˈtʃɪd.ən/", "mắng mỏ, khiển trách", "She chided the boy for being late."),
    ("choose", "/tʃuːz/", "chose", "/tʃoʊz/", "chosen", "/ˈtʃoʊ.zən/", "chọn lựa", "They chose the best option."),
    ("clad", "/klæd/", "clad", "/klæd/", "clad", "/klæd/", "mặc áo, che phủ", "The hills were clad in mist."),
    ("clap", "/klæp/", "clapped / clapt", "/klæpt/", "clapped / clapt", "/klæpt/", "vỗ tay", "The audience clapped loudly."),
    ("cleave", "/kliːv/", "clove / cleft / cleaved", "/kloʊv/", "cloven / cleft", "/ˈkloʊ.vən/", "chẻ đôi, tách ra", "He cleft the log with an axe."),
    ("cling", "/klɪŋ/", "clung", "/klʌŋ/", "clung", "/klʌŋ/", "bám chặt, dính vào", "She clung to her mother's hand."),
    ("clothe", "/kloʊð/", "clad / clothed", "/klæd/", "clad / clothed", "/klæd/", "mặc quần áo cho", "She clothed the children warmly."),
    ("come", "/kʌm/", "came", "/keɪm/", "come", "/kʌm/", "đến, tới", "They came home late last night."),
    ("cost", "/kɒst/", "cost", "/kɒst/", "cost", "/kɒst/", "có giá là, tốn kém", "The ticket cost fifty dollars."),
    ("creep", "/kriːp/", "crept", "/krept/", "crept", "/krept/", "bò, trườn, lén lút", "The cat crept toward the bird."),
    ("crow", "/kroʊ/", "crew / crowed", "/kruː/", "crowed", "/kroʊd/", "gáy (gà), reo vui", "The rooster crew at dawn."),
    ("cut", "/kʌt/", "cut", "/kʌt/", "cut", "/kʌt/", "cắt, chặt", "He cut the paper into strips."),
    ("dare", "/deər/", "dared / durst", "/deərd/", "dared", "/deərd/", "dám, thách thức", "No one durst speak up."),
    ("deal", "/diːl/", "dealt", "/delt/", "dealt", "/delt/", "giao dịch, giải quyết", "She dealt with the customer complaint."),
    ("dig", "/dɪɡ/", "dug", "/dʌɡ/", "dug", "/dʌɡ/", "đào bới", "They dug a deep hole in the garden."),
    ("dive", "/daɪv/", "dived / dove", "/daɪvd/ / /doʊv/", "dived", "/daɪvd/", "lặn, nhảy lao xuống", "He dove into the cool pool."),
    ("do", "/duː/", "did", "/dɪd/", "done", "/dʌn/", "làm, thực hiện", "She did her homework carefully."),
    ("draw", "/drɔː/", "drew", "/druː/", "drawn", "/drɔːn/", "vẽ, kéo", "He drew a picture of a cat."),
    ("dream", "/driːm/", "dreamt / dreamed", "/dremt/", "dreamt / dreamed", "/dremt/", "mơ ước, chiêm bao", "I dreamt of traveling the world."),
    ("drink", "/drɪŋk/", "drank", "/dræŋk/", "drunk", "/drʌŋk/", "uống", "She drank a glass of water."),
    ("drive", "/draɪv/", "drove", "/droʊv/", "driven", "/ˈdrɪv.ən/", "lái xe", "He drove safely along the road."),
    ("dwell", "/dwel/", "dwelt / dwelled", "/dwelt/", "dwelt / dwelled", "/dwelt/", "trú ngụ, ở", "They dwelt in a peaceful village."),
    ("eat", "/iːt/", "ate", "/eɪt/", "eaten", "/ˈiː.tən/", "ăn", "We ate dinner together."),
    ("fall", "/fɔːl/", "fell", "/fel/", "fallen", "/ˈfɔː.lən/", "ngã, rơi", "Leaves fell from the trees."),
    ("feed", "/fiːd/", "fed", "/fed/", "fed", "/fed/", "cho ăn, nuôi dưỡng", "He fed the cat in the morning."),
    ("feel", "/fiːl/", "felt", "/felt/", "felt", "/felt/", "cảm thấy", "I felt very excited about the trip."),
    ("fight", "/faɪt/", "fought", "/fɔːt/", "fought", "/fɔːt/", "chiến đấu, đánh nhau", "Soldiers fought bravely."),
    ("find", "/faɪnd/", "found", "/faʊnd/", "found", "/faʊnd/", "tìm thấy", "She found her missing keys."),
    ("fit", "/fɪt/", "fit / fitted", "/fɪt/", "fit / fitted", "/fɪt/", "vừa vặn, hợp", "The coat fit him well."),
    ("flee", "/fliː/", "fled", "/fled/", "fled", "/fled/", "chạy trốn, tẩu thoát", "The suspect fled from the scene."),
    ("fling", "/flɪŋ/", "flung", "/flʌŋ/", "flung", "/flʌŋ/", "quăng, ném mạnh", "She flung the door open."),
    ("fly", "/flaɪ/", "flew", "/fluː/", "flown", "/floʊn/", "bay", "The birds flew south for winter."),
    ("forbear", "/fɔːrˈbeər/", "forbore", "/fɔːrˈbɔːr/", "forborne", "/fɔːrˈbɔːrn/", "nhịn, kiềm chế", "He forbore to express his anger."),
    ("forbid", "/fərˈbɪd/", "forbade / forbad", "/fərˈbæd/", "forbidden", "/fərˈbɪd.ən/", "cấm đoán", "Swimming was forbidden here."),
    ("forecast", "/ˈfɔːr.kæst/", "forecast", "/ˈfɔːr.kæst/", "forecast", "/ˈfɔːr.kæst/", "dự báo thời tiết/tương lai", "They forecast rain for tomorrow."),
    ("foresee", "/fɔːrˈsiː/", "foresaw", "/fɔːrˈsɔː/", "foreseen", "/fɔːrˈsiːn/", "thấy trước, đoán trước", "She foresaw the consequences."),
    ("foretell", "/fɔːrˈtel/", "foretold", "/fɔːrˈtoʊld/", "foretold", "/fɔːrˈtoʊld/", "nói trước, báo trước", "The prophet foretold the victory."),
    ("forget", "/fərˈɡet/", "forgot", "/fərˈɡɒt/", "forgotten", "/fərˈɡɒt.ən/", "quên", "Don't forget your password."),
    ("forgive", "/fərˈɡɪv/", "forgave", "/fərˈɡeɪv/", "forgiven", "/fərˈɡɪv.ən/", "tha thứ", "She forgave him for his mistake."),
    ("forsake", "/fərˈseɪk/", "forsook", "/fərˈsʊk/", "forsaken", "/fərˈseɪ.kən/", "từ bỏ, ruồng bỏ", "He never forsook his principles."),
    ("freeze", "/friːz/", "froze", "/froʊz/", "frozen", "/ˈfroʊ.zən/", "đóng băng, đông cứng", "The lake froze during winter."),
    ("get", "/ɡet/", "got", "/ɡɒt/", "got / gotten", "/ˈɡɒt.ən/", "nhận được, trở nên", "He got an email from his friend."),
    ("gild", "/ɡɪld/", "gilt / gilded", "/ɡɪlt/", "gilt / gilded", "/ɡɪlt/", "mạ vàng", "The frame was gilded in gold."),
    ("give", "/ɡɪv/", "gave", "/ɡeɪv/", "given", "/ˈɡɪv.ən/", "cho, tặng", "She gave me a nice gift."),
    ("go", "/ɡoʊ/", "went", "/went/", "gone", "/ɡɒn/", "đi", "They went to Paris last summer."),
    ("grind", "/ɡraɪnd/", "ground", "/ɡraʊnd/", "ground", "/ɡraʊnd/", "nghiền, xay", "He ground fresh coffee beans."),
    ("grow", "/ɡroʊ/", "grew", "/ɡruː/", "grown", "/ɡroʊn/", "lớn lên, trồng", "The company grew rapidly."),
    ("hamstring", "/ˈhæm.strɪŋ/", "hamstrung", "/ˈhæm.strʌŋ/", "hamstrung", "/ˈhæm.strʌŋ/", "làm què, làm tê liệt", "The law hamstrung the police."),
    ("hang", "/hæŋ/", "hung", "/hʌŋ/", "hung", "/hʌŋ/", "treo", "She hung the picture on the wall."),
    ("have", "/hæv/", "had", "/hæd/", "had", "/hæd/", "có, sở hữu", "We had a great conversation."),
    ("hear", "/hɪər/", "heard", "/hɜːrd/", "heard", "/hɜːrd/", "nghe thấy", "Did you hear that strange noise?"),
    ("heave", "/hiːv/", "hove / heaved", "/hoʊv/", "hove / heaved", "/hoʊv/", "nâng lên, thở dốc", "He heaved a heavy sigh."),
    ("hew", "/hjuː/", "hewed", "/hjuːd/", "hewn / hewed", "/hjuːn/", "đẽo, chặt bằng rìu", "They hewed wood from the forest."),
    ("hide", "/haɪd/", "hid", "/hɪd/", "hidden", "/ˈhɪd.ən/", "trốn, giấu giếm", "The cat hid under the sofa."),
    ("hit", "/hɪt/", "hit", "/hɪt/", "hit", "/hɪt/", "đánh, va trúng", "The ball hit the window."),
    ("hold", "/hoʊld/", "held", "/held/", "held", "/held/", "cầm, nắm, tổ chức", "They held an international meeting."),
    ("hurt", "/hɜːrt/", "hurt", "/hɜːrt/", "hurt", "/hɜːrt/", "làm tổn thương, đau", "His knee hurt after running."),
    ("inlay", "/ɪnˈleɪ/", "inlaid", "/ɪnˈleɪd/", "inlaid", "/ɪnˈleɪd/", "khảm, cẩn", "The wooden box was inlaid with silver."),
    ("keep", "/kiːp/", "kept", "/kept/", "kept", "/kept/", "giữ gìn, duy trì", "She kept her promise."),
    ("kneel", "/niːl/", "knelt / kneeled", "/nelt/", "knelt / kneeled", "/nelt/", "quỳ gối", "He knelt down to propose."),
    ("knit", "/nɪt/", "knit / knitted", "/nɪt/", "knit / knitted", "/nɪt/", "đan len, liên kết", "Grandmother knit a wool scarf."),
    ("know", "/noʊ/", "knew", "/njuː/", "known", "/noʊn/", "biết, hiểu", "I knew the correct answer."),
    ("lade", "/leɪd/", "laded", "/ˈleɪ.dɪd/", "laden / laded", "/ˈleɪ.dən/", "chất tải, chở nặng", "The ship was heavily laden."),
    ("lay", "/leɪ/", "laid", "/leɪd/", "laid", "/leɪd/", "đặt, để, đẻ trứng", "She laid the book on the table."),
    ("lead", "/liːd/", "led", "/led/", "led", "/led/", "dẫn dắt, lãnh đạo", "He led the team to success."),
    ("lean", "/liːn/", "leant / leaned", "/lent/", "leant / leaned", "/lent/", "dựa, tựa vào", "He leaned against the railing."),
    ("leap", "/liːp/", "leapt / leaped", "/lept/", "leapt / leaped", "/lept/", "nhảy vọt, phóng qua", "The deer leapt over the fence."),
    ("learn", "/lɜːrn/", "learnt / learned", "/lɜːrnt/", "learnt / learned", "/lɜːrnt/", "học hỏi", "We learned 48 units thoroughly."),
    ("leave", "/liːv/", "left", "/left/", "left", "/left/", "rời đi, để lại", "The train left the station on time."),
    ("lend", "/lend/", "lent", "/lent/", "lent", "/lent/", "cho vay, cho mượn", "He lent me his umbrella."),
    ("let", "/let/", "let", "/let/", "let", "/let/", "để cho, cho phép", "Let me help you with that."),
    ("lie", "/laɪ/", "lay", "/leɪ/", "lain", "/leɪn/", "nằm", "She lay on the grass looking at the sky."),
    ("light", "/laɪt/", "lit / lighted", "/lɪt/", "lit / lighted", "/lɪt/", "thắp sáng, đốt", "He lit the candle in the room."),
    ("lose", "/luːz/", "lost", "/lɒst/", "lost", "/lɒst/", "làm mất, thua cuộc", "I lost my passport."),
    ("make", "/meɪk/", "made", "/meɪd/", "made", "/meɪd/", "làm, chế tạo", "She made a delicious cake."),
    ("mean", "/miːn/", "meant", "/ment/", "meant", "/ment/", "có nghĩa là", "What do you mean by that?"),
    ("meet", "/miːt/", "met", "/met/", "met", "/met/", "gặp gỡ", "They met at the cafe."),
    ("melt", "/melt/", "melted", "/ˈmel.tɪd/", "molten / melted", "/ˈmoʊl.tən/", "tan chảy", "The snow melted in spring."),
    ("miscast", "/ˌmɪsˈkæst/", "miscast", "/ˌmɪsˈkæst/", "miscast", "/ˌmɪsˈkæst/", "giao sai vai trò", "The actor was miscast in the film."),
    ("misdeal", "/ˌmɪsˈdiːl/", "misdealt", "/ˌmɪsˈdelt/", "misdealt", "/ˌmɪsˈdelt/", "chia bài sai, xử lý nhầm", "The dealer misdealt the cards."),
    ("misgive", "/mɪsˈɡɪv/", "misgave", "/mɪsˈɡeɪv/", "misgiven", "/mɪsˈɡɪv.ən/", "lo ngại, e ngại", "Her heart misgave her."),
    ("mishear", "/ˌmɪsˈhɪər/", "misheard", "/ˌmɪsˈhɜːrd/", "misheard", "/ˌmɪsˈhɜːrd/", "nghe nhầm", "I misheard what she said."),
    ("mishit", "/ˌmɪsˈhɪt/", "mishit", "/ˌmɪsˈhɪt/", "mishit", "/ˌmɪsˈhɪt/", "đánh trượt, sút hỏng", "The striker mishit the ball."),
    ("mislay", "/ˌmɪsˈleɪ/", "mislaid", "/ˌmɪsˈleɪd/", "mislaid", "/ˌmɪsˈleɪd/", "để thất lạc", "She mislaid her spectacles."),
    ("mislead", "/ˌmɪsˈliːd/", "misled", "/ˌmɪsˈled/", "misled", "/ˌmɪsˈled/", "làm lạc đường, đánh lừa", "The advertisements misled consumers."),
    ("misread", "/ˌmɪsˈriːd/", "misread", "/ˌmɪsˈred/", "misread", "/ˌmɪsˈred/", "đọc sai, hiểu sai", "I misread the instructions."),
    ("misspell", "/ˌmɪsˈspel/", "misspelt / misspelled", "/ˌmɪsˈspelt/", "misspelt / misspelled", "/ˌmɪsˈspelt/", "viết sai chính tả", "You misspelt that English word."),
    ("misspend", "/ˌmɪsˈspend/", "misspent", "/ˌmɪsˈspent/", "misspent", "/ˌmɪsˈspent/", "tiêu xài hoang phí", "He misspent his youth."),
    ("mistake", "/mɪˈsteɪk/", "mistook", "/mɪˈstʊk/", "mistaken", "/mɪˈsteɪ.kən/", "nhận nhầm, phạm sai lầm", "I mistook him for his brother."),
    ("misunderstand", "/ˌmɪs.ʌn.dəˈstænd/", "misunderstood", "/ˌmɪs.ʌn.dəˈstʊd/", "misunderstood", "/ˌmɪs.ʌn.dəˈstʊd/", "hiểu lầm", "They misunderstood the schedule."),
    ("mow", "/moʊ/", "mowed", "/moʊd/", "mown / mowed", "/moʊn/", "cắt cỏ", "He mowed the lawn this morning."),
    ("outbid", "/ˌaʊtˈbɪd/", "outbid", "/ˌaʊtˈbɪd/", "outbid", "/ˌaʊtˈbɪd/", "trả giá cao hơn", "She outbid all competitors."),
    ("outdo", "/ˌaʊtˈduː/", "outdid", "/ˌaʊtˈdɪd/", "outdone", "/ˌaʊtˈdʌn/", "vượt trội hơn, làm giỏi hơn", "He outdid everyone in the test."),
    ("outfight", "/ˌaʊtˈfaɪt/", "outfought", "/ˌaʊtˈfɔːt/", "outfought", "/ˌaʊtˈfɔːt/", "đánh thắng, vượt trội", "The boxer outfought his rival."),
    ("outgrow", "/ˌaʊtˈɡroʊ/", "outgrew", "/ˌaʊtˈɡruː/", "outgrown", "/ˌaʊtˈɡroʊn/", "lớn hơn, phát triển vượt", "He outgrow his winter coat."),
    ("output", "/ˈaʊt.pʊt/", "output", "/ˈaʊt.pʊt/", "output", "/ˈaʊt.pʊt/", "xuất ra, tạo ra sản lượng", "The factory output thousands of units."),
    ("outrun", "/ˌaʊtˈrʌn/", "outran", "/ˌaʊtˈræn/", "outrun", "/ˌaʊtˈrʌn/", "chạy nhanh hơn", "The cheetah outran the deer."),
    ("outsell", "/ˌaʊtˈsel/", "outsold", "/ˌaʊtˈsoʊld/", "outsold", "/ˌaʊtˈsoʊld/", "bán chạy hơn", "This phone outsold all others."),
    ("outshine", "/ˌaʊtˈʃaɪn/", "outshone", "/ˌaʊtˈʃɒn/", "outshone", "/ˌaʊtˈʃɒn/", "tỏa sáng hơn, vượt trội", "Her performance outshone the rest."),
    ("overbear", "/ˌoʊ.vərˈbeər/", "overbore", "/ˌoʊ.vərˈbɔːr/", "overborne", "/ˌoʊ.vərˈbɔːrn/", "áp đảo, đè bẹp", "She was overborne by his arguments."),
    ("overcast", "/ˈoʊ.vər.kæst/", "overcast", "/ˈoʊ.vər.kæst/", "overcast", "/ˈoʊ.vər.kæst/", "che phủ mây đen, u ám", "Dark clouds overcast the sky."),
    ("overcome", "/ˌoʊ.vəˈkʌm/", "overcame", "/ˌoʊ.vəˈkeɪm/", "overcome", "/ˌoʊ.vəˈkʌm/", "vượt qua, chiến thắng", "She overcame all hardships."),
    ("overdo", "/ˌoʊ.vəˈduː/", "overdid", "/ˌoʊ.vəˈdɪd/", "overdone", "/ˌoʊ.vəˈdʌn/", "làm quá mức", "Don't overdo the exercise."),
    ("overdraw", "/ˌoʊ.vəˈdrɔː/", "overdrew", "/ˌoʊ.vəˈdruː/", "overdrawn", "/ˌoʊ.vəˈdrɔːn/", "rút quá số dư ngân hàng", "He overdrew his checking account."),
    ("overeat", "/ˌoʊ.vəˈriːt/", "overate", "/ˌoʊ.vəˈreɪt/", "overeaten", "/ˌoʊ.vəˈriː.tən/", "ăn quá độ", "I overate at the buffet."),
    ("overfly", "/ˌoʊ.vəˈflaɪ/", "overflew", "/ˌoʊ.vəˈfluː/", "overflown", "/ˌoʊ.vəˈfloʊn/", "bay ngang qua", "The plane overflew the mountain."),
    ("overhang", "/ˌoʊ.vəˈhæŋ/", "overhung", "/ˌoʊ.vəˈhʌŋ/", "overhung", "/ˌoʊ.vəˈhʌŋ/", "nhô ra phía trên", "A cliff overhung the road."),
    ("overhear", "/ˌoʊ.vəˈhɪər/", "overheard", "/ˌoʊ.vəˈhɜːrd/", "overheard", "/ˌoʊ.vəˈhɜːrd/", "tình cờ nghe được", "I overheard their conversation."),
    ("overlay", "/ˌoʊ.vəˈleɪ/", "overlaid", "/ˌoʊ.vəˈleɪd/", "overlaid", "/ˌoʊ.vəˈleɪd/", "phủ lên trên", "Gold was overlaid on the surface."),
    ("overpay", "/ˌoʊ.vəˈpeɪ/", "overpaid", "/ˌoʊ.vəˈpeɪd/", "overpaid", "/ˌoʊ.vəˈpeɪd/", "trả tiền thừa", "They accidentally overpaid the invoice."),
    ("override", "/ˌoʊ.vəˈraɪd/", "overrode", "/ˌoʊ.vəˈroʊd/", "overridden", "/ˌoʊ.vəˈrɪd.ən/", "gạt bỏ, lấn át quyền", "The manager overrode the decision."),
    ("overrun", "/ˌoʊ.vəˈrʌn/", "overran", "/ˌoʊ.vəˈræn/", "overrun", "/ˌoʊ.vəˈrʌn/", "tràn ngập, vượt quá hạn", "The cost overran the budget."),
    ("oversee", "/ˌoʊ.vəˈsiː/", "oversaw", "/ˌoʊ.vəˈsɔː/", "overseen", "/ˌoʊ.vəˈsiːn/", "giám sát, trông coi", "He oversaw the entire construction."),
    ("oversell", "/ˌoʊ.vəˈsel/", "oversold", "/ˌoʊ.vəˈsoʊld/", "oversold", "/ˌoʊ.vəˈsoʊld/", "bán quá số lượng có thật", "The airline oversold the flight."),
    ("overshoot", "/ˌoʊ.vəˈʃuːt/", "overshot", "/ˌoʊ.vəˈʃɒt/", "overshot", "/ˌoʊ.vəˈʃɒt/", "bắn trượt, đi quá đà", "The plane overshot the runway."),
    ("oversleep", "/ˌoʊ.vəˈsliːp/", "overslept", "/ˌoʊ.vəˈslept/", "overslept", "/ˌoʊ.vəˈslept/", "ngủ quên", "I overslept and missed the bus."),
    ("overtake", "/ˌoʊ.vəˈteɪk/", "overtook", "/ˌoʊ.vəˈtʊk/", "overtaken", "/ˌoʊ.vəˈteɪ.kən/", "vượt qua (xe cộ, trình độ)", "The car overtook the truck safely."),
    ("overthrow", "/ˌoʊ.vəˈθroʊ/", "overthrew", "/ˌoʊ.vəˈθruː/", "overthrown", "/ˌoʊ.vəˈθroʊn/", "lật đổ (chính quyền)", "The rebels overthrew the dictator."),
    ("partake", "/pɑːrˈteɪk/", "partook", "/pɑːrˈtʊk/", "partaken", "/pɑːrˈteɪ.kən/", "tham dự, cùng ăn", "They partook in the celebration."),
    ("pay", "/peɪ/", "paid", "/peɪd/", "paid", "/peɪd/", "thanh toán, trả tiền", "She paid by credit card."),
    ("plead", "/pliːd/", "pled / pleaded", "/pled/", "pled / pleaded", "/pled/", "biện hộ, nài xin", "The accused pled not guilty."),
    ("prove", "/pruːv/", "proved", "/pruːvd/", "proven / proved", "/ˈpruː.vən/", "chứng minh", "The theory was proven right."),
    ("put", "/pʊt/", "put", "/pʊt/", "put", "/pʊt/", "đặt, để", "Put the key in your pocket."),
    ("quit", "/kwɪt/", "quit / quitted", "/kwɪt/", "quit / quitted", "/kwɪt/", "từ bỏ, nghỉ việc", "He quit his job last month."),
    ("read", "/riːd/", "read", "/red/", "read", "/red/", "đọc", "I read an interesting article."),
    ("rebind", "/ˌriːˈbaɪnd/", "rebound", "/ˌriːˈbaʊnd/", "rebound", "/ˌriːˈbaʊnd/", "đóng lại (bìa sách)", "They rebound the old dictionary."),
    ("rebuild", "/ˌriːˈbɪld/", "rebuilt", "/ˌriːˈbɪlt/", "rebuilt", "/ˌriːˈbɪlt/", "xây dựng lại", "The city rebuilt the bridge."),
    ("recast", "/ˌriːˈkæst/", "recast", "/ˌriːˈkæst/", "recast", "/ˌriːˈkæst/", "đúc lại, viết lại", "She recast her ideas into a plan."),
    ("redo", "/ˌriːˈduː/", "redid", "/ˌriːˈdɪd/", "redone", "/ˌriːˈdʌn/", "làm lại", "You must redo this exercise."),
    ("rehear", "/ˌriːˈhɪər/", "reheard", "/ˌriːˈhɜːrd/", "reheard", "/ˌriːˈhɜːrd/", "nghe lại (vụ án)", "The court reheard the case."),
    ("remake", "/ˌriːˈmeɪk/", "remade", "/ˌriːˈmeɪd/", "remade", "/ˌriːˈmeɪd/", "làm lại, quay lại phim", "They remade the classic movie."),
    ("rend", "/rend/", "rent / rended", "/rent/", "rent / rended", "/rent/", "xé rách, làm tan vỡ", "The grief rent her heart."),
    ("repay", "/rɪˈpeɪ/", "repaid", "/rɪˈpeɪd/", "repaid", "/rɪˈpeɪd/", "hoàn trả, đền đáp", "He repaid all his debts."),
    ("reread", "/ˌriːˈriːd/", "reread", "/ˌriːˈred/", "reread", "/ˌriːˈred/", "đọc lại", "I reread the chapter twice."),
    ("rerun", "/ˌriːˈrʌn/", "reran", "/ˌriːˈræn/", "rerun", "/ˌriːˈrʌn/", "chiếu lại, chạy lại", "The TV channel rerun the show."),
    ("resell", "/ˌriːˈsel/", "resold", "/ˌriːˈsoʊld/", "resold", "/ˌriːˈsoʊld/", "bán lại", "He resold the car at a profit."),
    ("reset", "/ˌriːˈset/", "reset", "/ˌriːˈset/", "reset", "/ˌriːˈset/", "thiết lập lại", "Please reset your password."),
    ("resit", "/ˌriːˈsɪt/", "resat", "/ˌriːˈsæt/", "resat", "/ˌriːˈsæt/", "thi lại", "Students had to resit the exam."),
    ("retake", "/ˌriːˈteɪk/", "retook", "/ˌriːˈtʊk/", "retaken", "/ˌriːˈteɪ.kən/", "chiếm lại, chụp lại, thi lại", "She retook the IELTS exam."),
    ("retell", "/ˌriːˈtel/", "retold", "/ˌriːˈtoʊld/", "retold", "/ˌriːˈtoʊld/", "kể lại", "He retold the story to his kids."),
    ("rewind", "/ˌriːˈwaɪnd/", "rewound", "/ˌriːˈwaʊnd/", "rewound", "/ˌriːˈwaʊnd/", "tua lại (băng, video)", "Rewind the video by 10 seconds."),
    ("rewrite", "/ˌriːˈraɪt/", "rewrote", "/ˌriːˈroʊt/", "rewritten", "/ˌriːˈrɪt.ən/", "viết lại", "She rewrote the entire essay."),
    ("rid", "/rɪd/", "rid / ridded", "/rɪd/", "rid / ridded", "/rɪd/", "giải thoát, loại bỏ", "We got rid of the old junk."),
    ("ride", "/raɪd/", "rode", "/roʊd/", "ridden", "/ˈrɪd.ən/", "cưỡi ngựa, lái xe đạp", "He rode his bicycle to school."),
    ("ring", "/rɪŋ/", "rang", "/ræŋ/", "rung", "/rʌŋ/", "rung chuông, gọi điện", "The school bell rang loudly."),
    ("rise", "/raɪz/", "rose", "/roʊz/", "risen", "/ˈrɪz.ən/", "dâng lên, mọc (mặt trời)", "The sun rose early today."),
    ("run", "/rʌn/", "ran", "/ræn/", "run", "/rʌn/", "chạy, vận hành", "He ran five kilometers."),
    ("saw", "/sɔː/", "sawed", "/sɔːd/", "sawn / sawed", "/sɔːn/", "cưa (gỗ)", "They sawed the branch off."),
    ("say", "/seɪ/", "said", "/sed/", "said", "/sed/", "nói", "She said goodbye with a smile."),
    ("see", "/siː/", "saw", "/sɔː/", "seen", "/siːn/", "nhìn thấy", "I saw a wonderful film."),
    ("seek", "/siːk/", "sought", "/sɔːt/", "sought", "/sɔːt/", "tìm kiếm, mưu cầu", "They sought advice from experts."),
    ("sell", "/sel/", "sold", "/soʊld/", "sold", "/soʊld/", "bán", "He sold his antique watch."),
    ("send", "/send/", "sent", "/sent/", "sent", "/sent/", "gửi đi", "She sent a message to her teacher."),
    ("set", "/set/", "set", "/set/", "set", "/set/", "đặt, thiết lập, lặn", "The sun set behind the mountains."),
    ("sew", "/soʊ/", "sewed", "/soʊd/", "sewn / sewed", "/soʊn/", "may vá, khâu", "She sewed a button onto the shirt."),
    ("shake", "/ʃeɪk/", "shook", "/ʃʊk/", "shaken", "/ˈʃeɪ.kən/", "rung, lắc, bắt tay", "They shook hands warmly."),
    ("shave", "/ʃeɪv/", "shaved / shove", "/ʃeɪvd/", "shaven / shaved", "/ˈʃeɪ.vən/", "cạo râu", "He shaved every morning."),
    ("shear", "/ʃɪər/", "sheared", "/ʃɪərd/", "shorn / sheared", "/ʃɔːrn/", "xén lông cừu", "The farmer sheared the sheep."),
    ("shed", "/ʃed/", "shed", "/ʃed/", "shed", "/ʃed/", "rơi rụng, trút bỏ", "Trees shed their leaves."),
    ("shine", "/ʃaɪn/", "shone / shined", "/ʃɒn/", "shone / shined", "/ʃɒn/", "tỏa sáng, chiếu rọi", "The sun shone brightly."),
    ("shit", "/ʃɪt/", "shit / shat", "/ʃɪt/ / /ʃæt/", "shit / shat", "/ʃɪt/ / /ʃæt/", "đi đại tiện (thông tục)", "The bird shat on the car."),
    ("shoe", "/ʃuː/", "shod / shoed", "/ʃɒd/", "shod / shoed", "/ʃɒd/", "đóng móng ngựa", "The blacksmith shod the horse."),
    ("shoot", "/ʃuːt/", "shot", "/ʃɒt/", "shot", "/ʃɒt/", "bắn, sút bóng", "The striker shot and scored."),
    ("show", "/ʃoʊ/", "showed", "/ʃoʊd/", "shown / showed", "/ʃoʊn/", "chỉ dẫn, cho xem", "Show me your work."),
    ("shrink", "/ʃrɪŋk/", "shrank", "/ʃræŋk/", "shrunk", "/ʃrʌŋk/", "co lại, thu nhỏ", "The sweater shrank in the wash."),
    ("shrive", "/ʃraɪv/", "shrove / shrived", "/ʃroʊv/", "shriven", "/ˈʃrɪv.ən/", "xưng tội, giải tội", "The priest shrove the penitent."),
    ("shut", "/ʃʌt/", "shut", "/ʃʌt/", "shut", "/ʃʌt/", "đóng lại", "Please shut the door quietly."),
    ("sing", "/sɪŋ/", "sang", "/sæŋ/", "sung", "/sʌŋ/", "hát", "She sang a sweet song."),
    ("sink", "/sɪŋk/", "sank", "/sæŋk/", "sunk", "/sʌŋk/", "chìm xuống", "The Titanic sank in 1912."),
    ("sit", "/sɪt/", "sat", "/sæt/", "sat", "/sæt/", "ngồi", "They sat by the fireplace."),
    ("slay", "/sleɪ/", "slew", "/sluː/", "slain", "/sleɪn/", "giết hại, tàn sát", "The knight slew the dragon."),
    ("sleep", "/sliːp/", "slept", "/slept/", "slept", "/slept/", "ngủ", "He slept for eight hours."),
    ("slide", "/slaɪd/", "slid", "/slɪd/", "slid", "/slɪd/", "trượt, lướt", "The children slid down the hill."),
    ("sling", "/slɪŋ/", "slung", "/slʌŋ/", "slung", "/slʌŋ/", "quăng, ném bằng ná", "David slung a stone at Goliath."),
    ("slink", "/slɪŋk/", "slunk", "/slʌŋk/", "slunk", "/slʌŋk/", "lẻn đi, lủi thủi", "The fox slunk into the bushes."),
    ("slit", "/slɪt/", "slit", "/slɪt/", "slit", "/slɪt/", "rạch, rọc", "He slit the envelope open."),
    ("smell", "/smel/", "smelt / smelled", "/smelt/", "smelt / smelled", "/smelt/", "ngửi thấy, có mùi", "The roses smelled wonderful."),
    ("smite", "/smaɪt/", "smote", "/smoʊt/", "smitten", "/ˈsmɪt.ən/", "đánh mạnh, giáng đòn", "He was smitten with love."),
    ("sow", "/soʊ/", "sowed", "/soʊd/", "sown / sowed", "/soʊn/", "gieo hạt", "Farmers sowed the wheat seeds."),
    ("speak", "/spiːk/", "spoke", "/spoʊk/", "spoken", "/ˈspoʊ.kən/", "nói chuyện", "She spoke fluent English."),
    ("speed", "/spiːd/", "sped / speeded", "/sped/", "sped / speeded", "/sped/", "tăng tốc, phóng nhanh", "The ambulance sped to the hospital."),
    ("spell", "/spel/", "spelt / spelled", "/spelt/", "spelt / spelled", "/spelt/", "đánh vần", "How do you spell your surname?"),
    ("spend", "/spend/", "spent", "/spent/", "spent", "/spent/", "tiêu xài, dành thời gian", "We spent the weekend studying."),
    ("spill", "/spɪl/", "spilt / spilled", "/spɪlt/", "spilt / spilled", "/spɪlt/", "làm tràn, đổ nước", "He accidentally spilt the milk."),
    ("spin", "/spɪn/", "spun", "/spʌn/", "spun", "/spʌn/", "quay tròn, giăng tơ", "The earth spins on its axis."),
    ("spit", "/spɪt/", "spat / spit", "/spæt/ / /spɪt/", "spat / spit", "/spæt/ / /spɪt/", "khạc nhổ", "Spitting on the street is banned."),
    ("split", "/splɪt/", "split", "/splɪt/", "split", "/splɪt/", "chẻ đôi, phân chia", "They split the bill evenly."),
    ("spoil", "/spɔɪl/", "spoilt / spoiled", "/spɔɪlt/", "spoilt / spoiled", "/spɔɪlt/", "làm hỏng, chiều chuộng", "The rain spoilt our picnic."),
    ("spread", "/spred/", "spread", "/spred/", "spread", "/spred/", "lan tỏa, trải rộng", "News spread very fast."),
    ("spring", "/sprɪŋ/", "sprang", "/spræŋ/", "sprung", "/sprʌŋ/", "bật nhảy, nảy sinh", "Tears sprang to her eyes."),
    ("stand", "/stænd/", "stood", "/stʊd/", "stood", "/stʊd/", "đứng, chịu đựng", "Everyone stood up as he entered."),
    ("stave", "/steɪv/", "stove / staved", "/stoʊv/", "stove / staved", "/stoʊv/", "thủng, ngăn chặn", "They staved off bankruptcy."),
    ("steal", "/stiːl/", "stole", "/stoʊl/", "stolen", "/ˈstoʊ.lən/", "ăn trộm, đánh cắp", "The thief stole her handbag."),
    ("stick", "/stɪk/", "stuck", "/stʌk/", "stuck", "/stʌk/", "dán dính, mắc kẹt", "The stamp stuck firmly to the letter."),
    ("sting", "/stɪŋ/", "stung", "/stʌŋ/", "stung", "/stʌŋ/", "châm, đốt (ong, muỗi)", "A bee stung him on the arm."),
    ("stink", "/stɪŋk/", "stank", "/stæŋk/", "stunk", "/stʌŋk/", "bốc mùi hôi thối", "The garbage stank in the heat."),
    ("strew", "/struː/", "strewed", "/struːd/", "strewn / strewed", "/struːn/", "rải rác, vương vãi", "Flowers were strewn on the floor."),
    ("stride", "/straɪd/", "strode", "/stroʊd/", "stridden", "/ˈstrɪd.ən/", "sải bước dài", "He strode purposefully into the room."),
    ("strike", "/straɪk/", "struck", "/strʌk/", "struck / stricken", "/ˈstrɪk.ən/", "đánh đập, đình công", "Lightning struck the tower."),
    ("string", "/strɪŋ/", "strung", "/strʌŋ/", "strung", "/strʌŋ/", "xâu chuỗi, căng dây", "She strung the beads on a wire."),
    ("strip", "/strɪp/", "stripped / stript", "/strɪpt/", "stripped / stript", "/strɪpt/", "cởi bỏ, tước đoạt", "He stripped the old wallpaper."),
    ("strive", "/straɪv/", "strove", "/stroʊv/", "striven", "/ˈstrɪv.ən/", "cố gắng, phấn đấu", "We strive for excellence."),
    ("sublet", "/ˌsʌbˈlet/", "sublet", "/ˌsʌbˈlet/", "sublet", "/ˌsʌbˈlet/", "cho thuê lại", "They sublet the second floor."),
    ("sunburn", "/ˈsʌn.bɜːrn/", "sunburned / sunburnt", "/ˈsʌn.bɜːrnt/", "sunburned / sunburnt", "/ˈsʌn.bɜːrnt/", "cháy nắng", "Her skin was sunburnt."),
    ("swear", "/sweər/", "swore", "/swɔːr/", "sworn", "/swɔːrn/", "thề, chửi thề", "He swore to tell the whole truth."),
    ("sweat", "/swet/", "sweat / sweated", "/swet/", "sweat / sweated", "/swet/", "đổ mồ hôi", "He sweat profusely after running."),
    ("sweep", "/swiːp/", "swept", "/swept/", "swept", "/swept/", "quét dọn", "She swept the courtyard clean."),
    ("swell", "/swel/", "swelled", "/sweld/", "swollen / swelled", "/ˈswoʊ.lən/", "sưng lên, phồng to", "His ankle was swollen after the twist."),
    ("swim", "/swɪm/", "swam", "/swæm/", "swum", "/swʌm/", "bơi lội", "We swam across the clear lake."),
    ("swing", "/swɪŋ/", "swung", "/swʌŋ/", "swung", "/swʌŋ/", "đu đưa, xoay tròn", "The monkey swung from branch to branch."),
    ("take", "/teɪk/", "took", "/tʊk/", "taken", "/ˈteɪ.kən/", "cầm, lấy, đưa đi", "She took a photo of the sunset."),
    ("teach", "/tiːtʃ/", "taught", "/tɔːt/", "taught", "/tɔːt/", "dạy học", "Teacher Mai Phuong taught grammar well."),
    ("tear", "/teər/", "tore", "/tɔːr/", "torn", "/tɔːrn/", "xé rách", "He tore the envelope open."),
    ("tell", "/tel/", "told", "/toʊld/", "told", "/toʊld/", "kể, bảo", "She told me the whole truth."),
    ("think", "/θɪŋk/", "thought", "/θɔːt/", "thought", "/θɔːt/", "suy nghĩ", "I thought about your suggestion."),
    ("thrive", "/θraɪv/", "throve / thrived", "/θroʊv/", "thriven / thrived", "/ˈθrɪv.ən/", "phát đạt, thịnh vượng", "The business thrived in the new market."),
    ("throw", "/θroʊ/", "threw", "/θruː/", "thrown", "/θroʊn/", "ném, quăng", "He threw the ball to his teammate."),
    ("thrust", "/θrʌst/", "thrust", "/θrʌst/", "thrust", "/θrʌst/", "đẩy mạnh, ấn sâu", "She thrust the key into the lock."),
    ("tread", "/tred/", "trod", "/trɒd/", "trodden / trod", "/ˈtrɒd.ən/", "giẫm đạp, bước đi", "Tread softly on the grass."),
    ("unbend", "/ʌnˈbend/", "unbent", "/ʌnˈbent/", "unbent", "/ʌnˈbent/", "thẳng ra, thư giãn", "He unbent his back after working."),
    ("underbid", "/ˌʌn.dəˈbɪd/", "underbid", "/ˌʌn.dəˈbɪd/", "underbid", "/ˌʌn.dəˈbɪd/", "bỏ giá thấp hơn", "They underbid other contractors."),
    ("undercut", "/ˌʌn.dəˈkʌt/", "undercut", "/ˌʌn.dəˈkʌt/", "undercut", "/ˌʌn.dəˈkʌt/", "bán phá giá, hạ giá", "Small stores were undercut by big malls."),
    ("undergo", "/ˌʌn.dəˈɡoʊ/", "underwent", "/ˌʌn.dəˈwent/", "undergone", "/ˌʌn.dəˈɡɒn/", "trải qua (thử thách, phẫu thuật)", "She underwent a successful surgery."),
    ("underlie", "/ˌʌn.dəˈlaɪ/", "underlay", "/ˌʌn.dəˈleɪ/", "underlain", "/ˌʌn.dəˈleɪn/", "nằm dưới, làm nền tảng", "Trust underlies any strong relationship."),
    ("underpay", "/ˌʌn.dəˈpeɪ/", "underpaid", "/ˌʌn.dəˈpeɪd/", "underpaid", "/ˌʌn.dəˈpeɪd/", "trả lương thấp", "Many workers were underpaid."),
    ("undersell", "/ˌʌn.dəˈsel/", "undersold", "/ˌʌn.dəˈsoʊld/", "undersold", "/ˌʌn.dəˈsoʊld/", "bán rẻ hơn đối thủ", "They undersold all competitors."),
    ("understand", "/ˌʌn.dəˈstænd/", "understood", "/ˌʌn.dəˈstʊd/", "understood", "/ˌʌn.dəˈstʊd/", "thấu hiểu", "I understood the grammar rule completely."),
    ("undertake", "/ˌʌn.dəˈteɪk/", "undertook", "/ˌʌn.dəˈtʊk/", "undertaken", "/ˌʌn.dəˈteɪ.kən/", "đảm nhận, cam kết", "She undertook the big project."),
    ("underwrite", "/ˌʌn.dəˈraɪt/", "underwrote", "/ˌʌn.dəˈroʊt/", "underwritten", "/ˌʌn.dəˈrɪt.ən/", "bảo hiểm, bảo lãnh", "The bank underwrote the bond issue."),
    ("undo", "/ʌnˈduː/", "undid", "/ʌnˈdɪd/", "undone", "/ʌnˈdʌn/", "hủy thao tác, tháo gỡ", "You can undo the last change."),
    ("unfreeze", "/ʌnˈfriːz/", "unfroze", "/ʌnˈfroʊz/", "unfrozen", "/ʌnˈfroʊ.zən/", "làm rã đông, giải tỏa", "The bank unfroze the account."),
    ("unhang", "/ʌnˈhæŋ/", "unhung", "/ʌnˈhʌŋ/", "unhung", "/ʌnˈhʌŋ/", "tháo xuống", "He unhung the picture."),
    ("unhide", "/ʌnˈhaɪd/", "unhid", "/ʌnˈhɪd/", "unhidden", "/ʌnˈhɪd.ən/", "làm lộ diện, bỏ ẩn", "Unhide the columns in the spreadsheet."),
    ("unknit", "/ʌnˈnɪt/", "unknit / unknitted", "/ʌnˈnɪt/", "unknit / unknitted", "/ʌnˈnɪt/", "tháo len", "She unknit the faulty rows."),
    ("unlade", "/ʌnˈleɪd/", "unladed", "/ʌnˈleɪ.dɪd/", "unladen / unladed", "/ʌnˈleɪ.dən/", "dỡ hàng khỏi tàu", "The crew unladed the cargo."),
    ("unlay", "/ʌnˈleɪ/", "unlaid", "/ʌnˈleɪd/", "unlaid", "/ʌnˈleɪd/", "tháo dây thừng", "He unlaid the strands of rope."),
    ("unlearn", "/ʌnˈlɜːrn/", "unlearnt / unlearned", "/ʌnˈlɜːrnt/", "unlearnt / unlearned", "/ʌnˈlɜːrnt/", "quên đi thói quen xấu", "It is hard to unlearn bad habits."),
    ("unlock", "/ʌnˈlɒk/", "unlocked", "/ʌnˈlɒkt/", "unlocked", "/ʌnˈlɒkt/", "mở khóa", "He unlocked the front door."),
    ("unmake", "/ʌnˈmeɪk/", "unmade", "/ʌnˈmeɪd/", "unmade", "/ʌnˈmeɪd/", "hủy bỏ, tháo dỡ", "What is done cannot be unmade."),
    ("unreeve", "/ʌnˈriːv/", "unrove / unreeved", "/ʌnˈroʊv/", "unrove / unreeved", "/ʌnˈroʊv/", "rút dây khỏi ròng rọc", "The sailor unrove the line."),
    ("unsay", "/ʌnˈseɪ/", "unsaid", "/ʌnˈsed/", "unsaid", "/ʌnˈsed/", "rút lại lời đã nói", "I wish I could unsay those words."),
    ("unseat", "/ʌnˈsiːt/", "unseated", "/ʌnˈsiː.tɪd/", "unseated", "/ʌnˈsiː.tɪd/", "hạ bệ, hất khỏi yên", "The scandal unseated the mayor."),
    ("unsew", "/ʌnˈsoʊ/", "unsewed", "/ʌnˈsoʊd/", "unsewn", "/ʌnˈsoʊn/", "tháo chỉ may", "She unsewed the hem of the dress."),
    ("unsling", "/ʌnˈslɪŋ/", "unslung", "/ʌnˈslʌŋ/", "unslung", "/ʌnˈslʌŋ/", "tháo dây đeo", "He unslung his heavy rifle."),
    ("unspin", "/ʌnˈspɪn/", "unspun", "/ʌnˈspʌn/", "unspun", "/ʌnˈspʌn/", "gỡ chỉ xoắn", "The wool was unspun."),
    ("unstick", "/ʌnˈstɪk/", "unstuck", "/ʌnˈstʌk/", "unstuck", "/ʌnˈstʌk/", "bóc ra, gỡ kẹt", "The adhesive came unstuck."),
    ("unstring", "/ʌnˈstrɪŋ/", "unstrung", "/ʌnˈstrʌŋ/", "unstrung", "/ʌnˈstrʌŋ/", "tháo dây đàn", "He unstrung the acoustic guitar."),
    ("unswear", "/ʌnˈsweər/", "unswore", "/ʌnˈswɔːr/", "unsworn", "/ʌnˈswɔːrn/", "từ bỏ lời thề", "He unswore his allegiance."),
    ("unteach", "/ʌnˈtiːtʃ/", "untaught", "/ʌnˈtɔːt/", "untaught", "/ʌnˈtɔːt/", "làm cho quên đi", "Experience untaught him the false theory."),
    ("unthink", "/ʌnˈθɪŋk/", "unthought", "/ʌnˈθɔːt/", "unthought", "/ʌnˈθɔːt/", "ngừng nghĩ về", "Try to unthink the negative thoughts."),
    ("untread", "/ʌnˈtred/", "untrod", "/ʌnˈtrɒd/", "untrodden", "/ʌnˈtrɒd.ən/", "quay ngược bước chân", "He untrod the path he had taken."),
    ("unweave", "/ʌnˈwiːv/", "unwove", "/ʌnˈwoʊv/", "unwoven", "/ʌnˈwoʊ.vən/", "tháo dệt", "Penelope unwove the tapestry each night."),
    ("unwind", "/ʌnˈwaɪnd/", "unwound", "/ʌnˈwaʊnd/", "unwound", "/ʌnˈwaʊnd/", "tháo ra, thư giãn", "Music helps me unwind after work."),
    ("uphold", "/ʌpˈhoʊld/", "upheld", "/ʌpˈheld/", "upheld", "/ʌpˈheld/", "ủng hộ, duy trì", "The court upheld the ruling."),
    ("uprise", "/ʌpˈraɪz/", "uprose", "/ʌpˈroʊz/", "uprisen", "/ʌpˈrɪz.ən/", "nổi dậy, dâng lên", "The villagers uprose against the tyrant."),
    ("upset", "/ʌpˈset/", "upset", "/ʌpˈset/", "upset", "/ʌpˈset/", "làm khó chịu, lật úp", "The bad news upset everyone."),
    ("wake", "/weɪk/", "woke / waked", "/woʊk/", "woken / waked", "/ˈwoʊ.kən/", "thức dậy", "I woke up at six o'clock."),
    ("waylay", "/weɪˈleɪ/", "waylaid", "/weɪˈleɪd/", "waylaid", "/weɪˈleɪd/", "mai phục, chặn đường", "Bandits waylaid travelers."),
    ("wear", "/weər/", "wore", "/wɔːr/", "worn", "/wɔːrn/", "mặc, đeo, hao mòn", "She wore a lovely dress."),
    ("weave", "/wiːv/", "wove / weaved", "/woʊv/", "woven / weaved", "/ˈwoʊ.vən/", "dệt, đan", "They wove a traditional carpet."),
    ("wed", "/wed/", "wed / wedded", "/wed/", "wed / wedded", "/wed/", "kết hôn", "They were wed in a private chapel."),
    ("weep", "/wiːp/", "wept", "/wept/", "wept", "/wept/", "khóc lóc", "She wept tears of joy."),
    ("wet", "/wet/", "wet / wetted", "/wet/", "wet / wetted", "/wet/", "làm ướt", "Rain wet the streets."),
    ("win", "/wɪn/", "won", "/wʌn/", "won", "/wʌn/", "chiến thắng", "She won first prize in the contest."),
    ("wind", "/waɪnd/", "wound", "/waʊnd/", "wound", "/waʊnd/", "cuộn lại, lên dây cót", "He wound the grandfather clock."),
    ("withdraw", "/wɪðˈdrɔː/", "withdrew", "/wɪðˈdruː/", "withdrawn", "/wɪðˈdrɔːn/", "rút lui, rút tiền", "She withdrew money from the ATM."),
    ("withhold", "/wɪðˈhoʊld/", "withheld", "/wɪðˈheld/", "withheld", "/wɪðˈheld/", "giữ lại, từ chối đưa", "The employer withheld payment."),
    ("withstand", "/wɪðˈstænd/", "withstood", "/wɪðˈstʊd/", "withstood", "/wɪðˈstʊd/", "chịu đựng, chống cự", "The bridge withstood the severe flood."),
    ("wring", "/rɪŋ/", "wrung", "/rʌŋ/", "wrung", "/rʌŋ/", "vắt kiệt (nước)", "She wrung out the wet towel."),
    ("write", "/raɪt/", "wrote", "/roʊt/", "written", "/ˈrɪt.ən/", "viết", "He wrote a letter to his friend."),
    ("backbite", "/ˈbæk.baɪt/", "backbit", "/ˈbæk.bɪt/", "backbitten", "/ˈbækˌbɪt.ən/", "nói xấu sau lưng", "Never backbite your friends."),
    ("breastfeed", "/ˈbrest.fiːd/", "breastfed", "/ˈbrest.fed/", "breastfed", "/ˈbrest.fed/", "cho con bú sữa mẹ", "She breastfed her baby for six months."),
    ("crossbreed", "/ˈkrɒs.briːd/", "crossbred", "/ˈkrɒs.bred/", "crossbred", "/ˈkrɒs.bred/", "lai giống", "They crossbred the plants for stronger yield."),
    ("deep-freeze", "/ˌdiːpˈfriːz/", "deep-froze", "/ˌdiːpˈfroʊz/", "deep-frozen", "/ˌdiːpˈfroʊ.zən/", "cấp đông sâu", "Deep-freeze the meat immediately."),
    ("disprove", "/dɪsˈpruːv/", "disproved", "/dɪsˈpruːvd/", "disproven / disproved", "/dɪsˈpruː.vən/", "bác bỏ, chứng minh sai", "The scientist disproved the myth."),
    ("floodlight", "/ˈflʌd.laɪt/", "floodlit / floodlighted", "/ˈflʌd.lɪt/", "floodlit / floodlighted", "/ˈflʌd.lɪt/", "chiếu sáng bằng đèn pha", "The stadium was floodlit for the match."),
    ("flyblow", "/ˈflaɪ.bloʊ/", "flyblew", "/ˈflaɪ.bluː/", "flyblown", "/ˈflaɪ.bloʊn/", "làm ôi thiu", "Meat was flyblown in the heat."),
    ("foreswear", "/fɔːrˈsweər/", "foreswore", "/fɔːrˈswɔːr/", "foresworn", "/fɔːrˈswɔːrn/", "từ thề, thề bỏ", "He foreswore smoking forever."),
    ("frostbite", "/ˈfrɒst.baɪt/", "frostbit", "/ˈfrɒst.bɪt/", "frostbitten", "/ˈfrɒstˌbɪt.ən/", "gây bỏng lạnh", "His fingers were frostbitten."),
    ("gainsay", "/ˌɡeɪnˈseɪ/", "gainsaid", "/ˌɡeɪnˈsed/", "gainsaid", "/ˌɡeɪnˈsed/", "chối cãi, phản bác", "Nobody could gainsay his evidence."),
    ("ghostwrite", "/ˈɡoʊst.raɪt/", "ghostwrote", "/ˈɡoʊst.roʊt/", "ghostwritten", "/ˈɡoʊstˌrɪt.ən/", "viết hộ, chấp bút", "She ghostwrote the politician's biography."),
    ("hand-feed", "/ˈhænd.fiːd/", "hand-fed", "/ˈhænd.fed/", "hand-fed", "/ˈhænd.fed/", "mớm mồi, cho ăn bằng tay", "Zookeepers hand-fed the panda cub."),
    ("handwrite", "/ˈhænd.raɪt/", "handwrote", "/ˈhænd.roʊt/", "handwritten", "/ˈhændˌrɪt.ən/", "viết tay", "She handwrote a warm thank-you letter."),
    ("interbreed", "/ˌɪn.təˈbriːd/", "interbred", "/ˌɪn.təˈbred/", "interbred", "/ˌɪn.təˈbred/", "giao phối cận huyết, lai", "Different species interbred naturally."),
    ("interweave", "/ˌɪn.təˈwiːv/", "interwove", "/ˌɪn.təˈwoʊv/", "interwoven", "/ˌɪn.təˈwoʊ.vən/", "dệt xen kẽ, đan kết", "Truth and fiction were interwoven."),
    ("lip-read", "/ˈlɪp.riːd/", "lip-read", "/ˈlɪp.red/", "lip-read", "/ˈlɪp.red/", "đọc mấp máy môi", "She lip-read what they were whispering."),
    ("offset", "/ˈɒf.set/", "offset", "/ˈɒf.set/", "offset", "/ˈɒf.set/", "bù đắp, đền bù", "Gains offset the previous losses."),
    ("outbleed", "/ˌaʊtˈbliːd/", "outbled", "/ˌaʊtˈbled/", "outbled", "/ˌaʊtˈbled/", "chảy máu nhiều hơn", "He outbled his opponent in endurance."),
    ("outbreed", "/ˌaʊtˈbriːd/", "outbred", "/ˌaʊtˈbred/", "outbred", "/ˌaʊtˈbred/", "sinh sản nhanh hơn", "The new strain outbred native insects."),
    ("outdrink", "/ˌaʊtˈdrɪŋk/", "outdrank", "/ˌaʊtˈdræŋk/", "outdrunk", "/ˌaʊtˈdrʌŋk/", "uống nhiều hơn người khác", "Nobody could outdrink him at the party."),
    ("outdrive", "/ˌaʊtˈdraɪv/", "outdrove", "/ˌaʊtˈdroʊv/", "outdriven", "/ˌaʊtˈdrɪv.ən/", "đánh bóng xa hơn (golf), lái giỏi hơn", "He outdrove all players on the 18th hole."),
    ("outlay", "/ˈaʊt.leɪ/", "outlaid", "/ˈaʊt.leɪd/", "outlaid", "/ˈaʊt.leɪd/", "tiêu phí, chi tiêu", "They outlaid large funds on technology."),
    ("outleap", "/ˌaʊtˈliːp/", "outleapt / outleaped", "/ˌaʊtˈlept/", "outleapt / outleaped", "/ˌaʊtˈlept/", "nhảy xa hơn", "The champion outleapt his rivals."),
    ("outlie", "/ˌaʊtˈlaɪ/", "outlay", "/ˌaʊtˈleɪ/", "outlain", "/ˌaʊtˈleɪn/", "nằm ngoài rìa", "Several rocks outlay the main reef."),
    ("outride", "/ˌaʊtˈraɪd/", "outrode", "/ˌaʊtˈroʊd/", "outridden", "/ˌaʊtˈrɪd.ən/", "cưỡi ngựa vượt trước, vượt qua giông bão", "The ship outrode the fierce storm."),
    ("outshoot", "/ˌaʊtˈʃuːt/", "outshot", "/ˌaʊtˈʃɒt/", "outshot", "/ˌaʊtˈʃɒt/", "bắn giỏi hơn", "The archer outshot his rivals easily."),
    ("outsing", "/ˌaʊtˈsɪŋ/", "outsang", "/ˌaʊtˈsæŋ/", "outsung", "/ˌaʊtˈsʌŋ/", "hát hay/vang hơn", "Her clear soprano outsang the chorus."),
    ("outsit", "/ˌaʊtˈsɪt/", "outsat", "/ˌaʊtˈsæt/", "outsat", "/ˌaʊtˈsæt/", "ngồi lâu hơn", "He outsat everyone during the debate."),
    ("outsleep", "/ˌaʊtˈsliːp/", "outslept", "/ˌaʊtˈslept/", "outslept", "/ˌaʊtˈslept/", "ngủ lâu hơn", "She outslept the entire household."),
    ("outsmell", "/ˌaʊtˈsmel/", "outsmelt / outsmelled", "/ˌaʊtˈsmelt/", "outsmelt / outsmelled", "/ˌaʊtˈsmelt/", "thính mũi hơn", "The bloodhound outsmelt all other dogs."),
    ("outspeak", "/ˌaʊtˈspiːk/", "outspoke", "/ˌaʊtˈspoʊk/", "outspoken", "/ˌaʊtˈspoʊ.kən/", "nói to hơn, bộc trực", "She outspoke in defense of her rights."),
    ("outspeed", "/ˌaʊtˈspiːd/", "outsped", "/ˌaʊtˈsped/", "outsped", "/ˌaʊtˈsped/", "vượt tốc độ", "The electric car outsped traditional models."),
    ("outspend", "/ˌaʊtˈspend/", "outspent", "/ˌaʊtˈspent/", "outspent", "/ˌaʊtˈspent/", "chi tiêu vượt mặt", "The campaign outspent its opponents."),
    ("outspin", "/ˌaʊtˈspɪn/", "outspun", "/ˌaʊtˈspʌn/", "outspun", "/ˌaʊtˈspʌn/", "quay nhanh hơn", "The new centrifuge outspun older units."),
    ("outspring", "/ˌaʊtˈsprɪŋ/", "outsprang", "/ˌaʊtˈspræŋ/", "outsprung", "/ˌaʊtˈsprʌŋ/", "bật nảy cao hơn", "The cat outsprang the fence."),
    ("outstand", "/ˌaʊtˈstænd/", "outstood", "/ˌaʊtˈstʊd/", "outstood", "/ˌaʊtˈstʊd/", "nổi bật, tồn đọng", "Several issues still outstood."),
    ("outswear", "/ˌaʊtˈsweər/", "outswore", "/ˌaʊtˈswɔːr/", "outsworn", "/ˌaʊtˈswɔːrn/", "chửi rủa át lời người khác", "The sailor outswore the pirate."),
    ("outswim", "/ˌaʊtˈswɪm/", "outswam", "/ˌaʊtˈswæm/", "outswum", "/ˌaʊtˈswʌm/", "bơi nhanh hơn", "The dolphin easily outswam the boat."),
    ("outthink", "/ˌaʊtˈθɪŋk/", "outthought", "/ˌaʊtˈθɔːt/", "outthought", "/ˌaʊtˈθɔːt/", "mưu mẹo hơn, nghĩ sâu hơn", "The grandmaster outthought his opponent."),
    ("outthrow", "/ˌaʊtˈθroʊ/", "outthrew", "/ˌaʊtˈθruː/", "outthrown", "/ˌaʊtˈθroʊn/", "ném xa hơn", "He outthrew all competitor javelins."),
    ("outwear", "/ˌaʊtˈweər/", "outwore", "/ˌaʊtˈwɔːr/", "outworn", "/ˌaʊtˈwɔːrn/", "bền hơn, làm hao mòn", "Leather shoes outwear fabric sneakers."),
    ("outwind", "/ˌaʊtˈwaɪnd/", "outwound", "/ˌaʊtˈwaʊnd/", "outwound", "/ˌaʊtˈwaʊnd/", "tháo cuộn ra ngoài", "He outwound the fishing line."),
    ("outwrite", "/ˌaʊtˈraɪt/", "outwrote", "/ˌaʊtˈroʊt/", "outwritten", "/ˌaʊtˈrɪt.ən/", "viết nhiều/nhanh hơn", "The author outwrote all his contemporaries."),
    ("overbid", "/ˌoʊ.vərˈbɪd/", "overbid", "/ˌoʊ.vərˈbɪd/", "overbid", "/ˌoʊ.vərˈbɪd/", "trả giá quá đà", "They overbid at the auction."),
    ("overblow", "/ˌoʊ.vərˈbloʊ/", "overblew", "/ˌoʊ.vərˈbluː/", "overblown", "/ˌoʊ.vərˈbloʊn/", "thổi quá trớn, phóng đại", "The media overblew the crisis."),
    ("overbreed", "/ˌoʊ.vərˈbriːd/", "overbred", "/ˌoʊ.vərˈbred/", "overbred", "/ˌoʊ.vərˈbred/", "nhân giống quá mức", "Overbred pets often have health issues."),
    ("overbuild", "/ˌoʊ.vərˈbɪld/", "overbuilt", "/ˌoʊ.vərˈbɪlt/", "overbuilt", "/ˌoʊ.vərˈbɪlt/", "xây dựng quá mức", "The district was overbuilt with condos."),
    ("overbuy", "/ˌoʊ.vərˈbaɪ/", "overbought", "/ˌoʊ.vərˈbɔːt/", "overbought", "/ˌoʊ.vərˈbɔːt/", "mua quá nhiều", "They overbought supplies before the holidays."),
    ("overfeed", "/ˌoʊ.vərˈfiːd/", "overfed", "/ˌoʊ.vərˈfed/", "overfed", "/ˌoʊ.vərˈfed/", "cho ăn quá no", "Do not overfeed the fish in the aquarium."),
    ("overgrow", "/ˌoʊ.vərˈɡroʊ/", "overgrew", "/ˌoʊ.vərˈɡruː/", "overgrown", "/ˌoʊ.vərˈɡroʊn/", "mọc tràn lan", "Weeds overgrew the path."),
    ("overlie", "/ˌoʊ.vərˈlaɪ/", "overlay", "/ˌoʊ.vərˈleɪ/", "overlain", "/ˌoʊ.vərˈleɪn/", "nằm đè lên trên", "Sandstone overlain by basalt."),
    ("overspend", "/ˌoʊ.vərˈspend/", "overspent", "/ˌoʊ.vərˈspent/", "overspent", "/ˌoʊ.vərˈspent/", "tiêu quá ngân sách", "The department overspent its budget."),
    ("overspill", "/ˌoʊ.vərˈspɪl/", "overspilt / overspilled", "/ˌoʊ.vərˈspɪlt/", "overspilt / overspilled", "/ˌoʊ.vərˈspɪlt/", "tràn ra ngoài", "Crowds overspilt into the streets."),
    ("overthink", "/ˌoʊ.vərˈθɪŋk/", "overthought", "/ˌoʊ.vərˈθɔːt/", "overthought", "/ˌoʊ.vərˈθɔːt/", "nghĩ ngợi quá mức", "Stop overthinking every small detail."),
    ("overwind", "/ˌoʊ.vərˈwaɪnd/", "overwound", "/ˌoʊ.vərˈwaʊnd/", "overwound", "/ˌoʊ.vərˈwaʊnd/", "vặn dây cót quá chặt", "He overwound the mechanical toy."),
    ("overwrite", "/ˌoʊ.vərˈraɪt/", "overwrote", "/ˌoʊ.vərˈroʊt/", "overwritten", "/ˌoʊ.vərˈrɪt.ən/", "ghi đè lên", "The new file overwrote the previous version."),
    ("proofread", "/ˈpruːf.riːd/", "proofread", "/ˈpruːf.red/", "proofread", "/ˈpruːf.red/", "đọc dò lỗi chính tả", "She proofread the manuscript carefully."),
    ("quick-freeze", "/ˌkwɪkˈfriːz/", "quick-froze", "/ˌkwɪkˈfroʊz/", "quick-frozen", "/ˌkwɪkˈfroʊ.zən/", "làm đông cấp tốc", "Quick-freeze the berries to keep vitamins."),
    ("reawake", "/ˌriː.əˈweɪk/", "reawoke", "/ˌriː.əˈwoʊk/", "reawoken", "/ˌriː.əˈwoʊ.kən/", "thức tỉnh lại", "His speech reawoke their passion."),
    ("refit", "/ˌriːˈfɪt/", "refit / refitted", "/ˌriːˈfɪt/", "refit / refitted", "/ˌriːˈfɪt/", "sửa chữa, tân trang tàu", "Engineers refit the container ship."),
    ("regrind", "/ˌriːˈɡraɪnd/", "reground", "/ˌriːˈɡraʊnd/", "reground", "/ˌriːˈɡraʊnd/", "mài lại, nghiền lại", "They reground the dull blades."),
    ("regrow", "/ˌriːˈɡroʊ/", "regrew", "/ˌriːˈɡruː/", "regrown", "/ˌriːˈɡroʊn/", "mọc lại", "The lizard regrew its lost tail."),
    ("rehang", "/ˌriːˈhæŋ/", "rehung", "/ˌriːˈhʌŋ/", "rehung", "/ˌriːˈhʌŋ/", "treo lại", "She rehung the painting in the gallery."),
    ("reknit", "/ˌriːˈnɪt/", "reknit / reknitted", "/ˌriːˈnɪt/", "reknit / reknitted", "/ˌriːˈnɪt/", "đan lại, liền lại xương", "The broken bone reknit naturally."),
    ("relay", "/rɪˈleɪ/", "relaid", "/rɪˈleɪd/", "relaid", "/rɪˈleɪd/", "đặt lại (đường ray, gạch)", "Workers relaid the railway tracks."),
    ("relearn", "/ˌriːˈlɜːrn/", "relearnt / relearned", "/ˌriːˈlɜːrnt/", "relearnt / relearned", "/ˌriːˈlɜːrnt/", "học lại từ đầu", "He relearnt English grammar foundations."),
    ("relight", "/ˌriːˈlaɪt/", "relit / relighted", "/ˌriːˈlɪt/", "relit / relighted", "/ˌriːˈlɪt/", "thắp sáng lại", "She relit the extinguished candle."),
    ("resend", "/ˌriːˈsend/", "resent", "/ˌriːˈsent/", "resent", "/ˌriːˈsent/", "gửi lại (email, tin nhắn)", "Please resend the confirmation email."),
    ("resew", "/ˌriːˈsoʊ/", "resewed", "/ˌriːˈsoʊd/", "resewn / resewed", "/ˌriːˈsoʊn/", "khâu lại", "The tailor resewed the loose pocket."),
    ("reteach", "/ˌriːˈtiːtʃ/", "retaught", "/ˌriːˈtɔːt/", "retaught", "/ˌriːˈtɔːt/", "dạy lại", "The tutor retaught the difficult unit."),
    ("rethink", "/ˌriːˈθɪŋk/", "rethought", "/ˌriːˈθɔːt/", "rethought", "/ˌriːˈθɔːt/", "suy nghĩ lại, cân nhắc lại", "We must rethink our strategy."),
    ("rewear", "/ˌriːˈweər/", "rewore", "/ˌriːˈwɔːr/", "reworn", "/ˌriːˈwɔːrn/", "mặc lại trang phục", "She rewore her favorite dress."),
    ("rough-hew", "/ˌrʌfˈhjuː/", "rough-hewed", "/ˌrʌfˈhjuːd/", "rough-hewn", "/ˌrʌfˈhjuːn/", "đẽo thô, tạo hình sơ bộ", "They rough-hewn timbers for the cabin."),
    ("sand-cast", "/ˈsænd.kæst/", "sand-cast", "/ˈsænd.kæst/", "sand-cast", "/ˈsænd.kæst/", "đúc bằng khuôn cát", "The iron gears were sand-cast."),
    ("sight-read", "/ˈsaɪt.riːd/", "sight-read", "/ˈsaɪt.red/", "sight-read", "/ˈsaɪt.red/", "xướng âm không chuẩn bị", "The pianist can sight-read any sheet music."),
    ("skywrite", "/ˈskaɪ.raɪt/", "skywrote", "/ˈskaɪ.roʊt/", "skywritten", "/ˈskaɪˌrɪt.ən/", "viết khói trên bầu trời", "The pilot skywrote a birthday message."),
    ("spoon-feed", "/ˈspuːn.fiːd/", "spoon-fed", "/ˈspuːn.fed/", "spoon-fed", "/ˈspuːn.fed/", "mớm cơm, chiều chuộng quá mức", "Do not spoon-feed all solutions to students."),
    ("spring-clean", "/ˌsprɪŋˈkliːn/", "spring-cleaned", "/ˌsprɪŋˈkliːnd/", "spring-cleaned", "/ˌsprɪŋˈkliːnd/", "tổng vệ sinh mùa xuân", "We spring-cleaned the whole house."),
    ("telecast", "/ˈtel.ɪ.kæst/", "telecast", "/ˈtel.ɪ.kæst/", "telecast", "/ˈtel.ɪ.kæst/", "phát hình trên tivi", "The ceremony was telecast worldwide."),
    ("test-drive", "/ˈtest.draɪv/", "test-drove", "/ˈtest.droʊv/", "test-driven", "/ˈtestˌdrɪv.ən/", "lái thử xe", "He test-drove the brand new car."),
    ("test-fly", "/ˈtest.flaɪ/", "test-flew", "/ˈtest.fluː/", "test-flown", "/ˈtestˌfloʊn/", "bay thử nghiệm", "Pilots test-flew the supersonic jet."),
    ("typewrite", "/ˈtaɪp.raɪt/", "typewrote", "/ˈtaɪp.roʊt/", "typewritten", "/ˈtaɪpˌrɪt.ən/", "đánh máy chữ", "He typewrote the legal document."),
    ("unbind", "/ʌnˈbaɪnd/", "unbound", "/ʌnˈbaʊnd/", "unbound", "/ʌnˈbaʊnd/", "mở trói, cởi trói", "She unbound the prisoner's hands."),
    ("unclothe", "/ʌnˈkloʊð/", "unclad / unclothed", "/ʌnˈklæd/", "unclad / unclothed", "/ʌnˈklæd/", "cởi bỏ quần áo", "The doctor asked him to unclothe."),
    ("underbuy", "/ˌʌn.dəˈbaɪ/", "underbought", "/ˌʌn.dəˈbɔːt/", "underbought", "/ˌʌn.dəˈbɔːt/", "mua dưới mức cần", "They underbought winter stock."),
    ("underfeed", "/ˌʌn.dəˈfiːd/", "underfed", "/ˌʌn.dəˈfed/", "underfed", "/ˌʌn.dəˈfed/", "thiếu ăn, bỏ đói", "The rescue dog was severely underfed."),
    ("undergird", "/ˌʌn.dəˈɡɜːrd/", "undergirt / undergirded", "/ˌʌn.dəˈɡɜːrt/", "undergirt / undergirded", "/ˌʌn.dəˈɡɜːrt/", "chống đỡ, gia cố bên dưới", "Solid principles undergird our project."),
    ("undraw", "/ʌnˈdrɔː/", "undrew", "/ʌnˈdruː/", "undrawn", "/ʌnˈdrɔːn/", "kéo mở rèm cửa", "She undrew the heavy curtains at dawn."),
    ("unhold", "/ʌnˈhoʊld/", "unheld", "/ʌnˈheld/", "unheld", "/ʌnˈheld/", "thả tay, buông ra", "He unheld her wrist gently."),
    ("untie", "/ʌnˈtaɪ/", "untied", "/ʌnˈtaɪd/", "untied", "/ʌnˈtaɪd/", "cởi dây, tháo nút", "She untied the ribbon on the gift."),
    ("upbuild", "/ʌpˈbɪld/", "upbuilt", "/ʌpˈbɪlt/", "upbuilt", "/ʌpˈbɪlt/", "xây dựng nâng tầm", "Education upbuilt the entire community."),
    ("uppercut", "/ˈʌp.ə.kʌt/", "uppercut", "/ˈʌp.ə.kʌt/", "uppercut", "/ˈʌp.ə.kʌt/", "đấm móc lên (boxing)", "The fighter landed a sharp uppercut.")
]

def build_catalog():
    data = []
    for item in IRREGULAR_VERBS_RAW:
        v1, v1_ipa, v2, v2_ipa, v3, v3_ipa, meaning, example = item
        data.append({
            "id": f"irv_{v1.replace(' ', '_')}",
            "v1": v1,
            "v1_ipa": v1_ipa,
            "v2": v2,
            "v2_ipa": v2_ipa,
            "v3": v3,
            "v3_ipa": v3_ipa,
            "meaning": meaning,
            "example": example,
            "source": "Oxford & Cambridge Irregular Verbs Standard"
        })

    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    target_path = os.path.join(base_dir, "data", "irregular_verbs.json")
    with open(target_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Successfully generated {len(data)} irregular verbs with full IPA to {target_path}")

if __name__ == "__main__":
    build_catalog()
